region: us
version: '2'
authtoken: 30xuQfJCJJmYeVjswNwl6PzcTt7_ZqSBdmMrJ3jJR5snPLAX
tunnels:
  exotel-app:
    addr: exotel-app:8003
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http